# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180326_1256'),
        ('users', '0004_auto_20180325_1430'),
    ]

    operations = [
    ]
