# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_busparameter_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='running_status',
            field=models.BooleanField(default=False),
        ),
    ]
