# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_auto_20180326_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
